-- local lint = require'lint'
--
-- lint.linters_by_ft = {
--   php = {'phpcs',},
-- }
--
-- vim.api.nvim_create_autocmd({ "InsertLeave" }, {
--   callback = function()
--     lint.try_lint()
--   end,
-- })
